# Generated by Django 4.2.16 on 2024-09-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingConfigsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='配置名称(KEY)')),
                ('content', models.TextField(blank=True, default='{}', null=True, verbose_name='配置内容(VALUE)格式JSON')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('comments', models.TextField(blank=True, help_text='备注信息。', null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '(SC)公共配置信息',
                'db_table': 'app_common_setting_configs',
            },
        ),
    ]
